export type QuestionMetadataSample = {
  id: string;
  title: string;
  question: string;
  referenceAnswer: string;
  studentAnswer: string;
  expectedPattern: string;
  expectedQuestionType: string;
  expectedAssessmentMode: string;
  expectedMainAbility: string;
  expectedRubricKeywords: string[];
};

export const questionMetadataSamples: QuestionMetadataSample[] = [
  {
    id: 'metadata_extraction_001',
    title: '信息提取：找原因',
    question: '根据原文，找出母亲改变主意的两个原因。',
    referenceAnswer: '一是她看见孩子一直坚持练习，二是老师说明孩子确实有进步。',
    studentAnswer: '母亲看到孩子坚持，也听老师说孩子有进步。',
    expectedPattern: 'information_extraction_v1',
    expectedQuestionType: '信息提取',
    expectedAssessmentMode: 'key_points',
    expectedMainAbility: '信息提取',
    expectedRubricKeywords: ['题干限定', '关键文本', '完整要点'],
  },
  {
    id: 'metadata_extraction_002',
    title: '信息提取：哪几件事',
    question: '文中写了哪几件表现父爱的事？',
    referenceAnswer: '父亲送我上学、在门口等我回家、为我留灯。',
    studentAnswer: '父亲送我上学，还等我回家。',
    expectedPattern: 'information_extraction_v1',
    expectedQuestionType: '信息提取',
    expectedAssessmentMode: 'key_points',
    expectedMainAbility: '信息提取',
    expectedRubricKeywords: ['题干限定', '关键文本', '完整要点'],
  },
  {
    id: 'metadata_extraction_003',
    title: '信息提取：找相关句子',
    question: '从文中找出描写父亲等待我的相关句子。',
    referenceAnswer: '父亲仍然习惯站在门口等我。',
    studentAnswer: '父亲站在门口等我。',
    expectedPattern: 'information_extraction_v1',
    expectedQuestionType: '信息提取',
    expectedAssessmentMode: 'key_points',
    expectedMainAbility: '信息提取',
    expectedRubricKeywords: ['题干限定', '关键文本'],
  },
  {
    id: 'metadata_extraction_004',
    title: '信息提取：哪些变化',
    question: '请根据文章内容，概括不同时期院子里的树有哪些变化。',
    referenceAnswer: '小时候枝叶茂盛，后来逐渐枯黄，最后又抽出新芽。',
    studentAnswer: '树先很茂盛，后来枯黄，最后长出新芽。',
    expectedPattern: 'information_extraction_v1',
    expectedQuestionType: '信息提取',
    expectedAssessmentMode: 'key_points',
    expectedMainAbility: '信息提取',
    expectedRubricKeywords: ['题干限定', '完整要点'],
  },
  {
    id: 'metadata_extraction_005',
    title: '信息提取：摘录依据',
    question: '从文中摘录一句能表现奶奶节俭的句子。',
    referenceAnswer: '奶奶总把旧布头收起来，说还能缝成新的鞋垫。',
    studentAnswer: '奶奶把旧布头收起来。',
    expectedPattern: 'information_extraction_v1',
    expectedQuestionType: '信息提取',
    expectedAssessmentMode: 'key_points',
    expectedMainAbility: '信息提取',
    expectedRubricKeywords: ['题干限定', '关键文本'],
  },
  {
    id: 'metadata_summary_001',
    title: '概括：主要内容',
    question: '请概括文章主要内容。',
    referenceAnswer: '文章回忆父亲送“我”上学和等待“我”回家的经历，表现了父亲深沉而无言的爱。',
    studentAnswer: '文章写父亲送我上学和等我回家。',
    expectedPattern: 'summary_v1',
    expectedQuestionType: '概括',
    expectedAssessmentMode: 'key_points',
    expectedMainAbility: '概括',
    expectedRubricKeywords: ['核心事件', '主题'],
  },
  {
    id: 'metadata_summary_002',
    title: '概括：主要写了什么',
    question: '选文主要写了什么？请简要概括。',
    referenceAnswer: '选文主要写父亲用旧自行车接送孩子，并在孩子长大后仍默默等待的经历。',
    studentAnswer: '选文写父亲接送孩子。',
    expectedPattern: 'summary_v1',
    expectedQuestionType: '概括',
    expectedAssessmentMode: 'key_points',
    expectedMainAbility: '概括',
    expectedRubricKeywords: ['主要对象', '核心事件'],
  },
  {
    id: 'metadata_summary_003',
    title: '概括：段落大意',
    question: '请概括这一段的段落大意。',
    referenceAnswer: '这一段写作者回家时发现父亲仍在门口等待，从而理解父亲的爱。',
    studentAnswer: '这一段写父亲在门口等作者。',
    expectedPattern: 'summary_v1',
    expectedQuestionType: '概括',
    expectedAssessmentMode: 'key_points',
    expectedMainAbility: '概括',
    expectedRubricKeywords: ['核心事件', '表达完整'],
  },
  {
    id: 'metadata_summary_004',
    title: '概括：故事情节',
    question: '请用简洁的语言概述本文的故事情节。',
    referenceAnswer: '本文写“我”误解母亲的严格，后来通过一件小事理解母亲良苦用心。',
    studentAnswer: '我一开始误解母亲，后来理解了她。',
    expectedPattern: 'summary_v1',
    expectedQuestionType: '概括',
    expectedAssessmentMode: 'key_points',
    expectedMainAbility: '概括',
    expectedRubricKeywords: ['核心事件', '表达完整'],
  },
  {
    id: 'metadata_summary_005',
    title: '概括：中心思想',
    question: '请概括本文的中心思想。',
    referenceAnswer: '文章通过叙写邻里互助的故事，赞美普通人之间真诚温暖的情感。',
    studentAnswer: '文章赞美了邻里之间的温暖。',
    expectedPattern: 'summary_v1',
    expectedQuestionType: '概括',
    expectedAssessmentMode: 'key_points',
    expectedMainAbility: '概括',
    expectedRubricKeywords: ['主题情感', '表达完整'],
  },
  {
    id: 'metadata_sentence_001',
    title: '句子含义：分析含义',
    question: '请分析“照亮了父亲对我的牵挂”的含义。',
    referenceAnswer: '“照亮”不是指灯光真正照亮，而是指作者通过这盏灯感受到父亲一直以来的关爱和牵挂。',
    studentAnswer: '父亲用灯给我照亮回家的路。',
    expectedPattern: 'sentence_meaning_v1',
    expectedQuestionType: '句子含义',
    expectedAssessmentMode: 'reasoning_chain',
    expectedMainAbility: '理解',
    expectedRubricKeywords: ['字面含义转换', '语境联系', '情感理解'],
  },
  {
    id: 'metadata_sentence_002',
    title: '句子含义：如何理解',
    question: '如何理解文中“他终于放慢了脚步”这句话？',
    referenceAnswer: '这句话写出人物愿意停下来面对问题，表现心理转变。',
    studentAnswer: '他走路变慢了。',
    expectedPattern: 'sentence_meaning_v1',
    expectedQuestionType: '句子含义',
    expectedAssessmentMode: 'reasoning_chain',
    expectedMainAbility: '理解',
    expectedRubricKeywords: ['字面含义转换', '语境联系'],
  },
  {
    id: 'metadata_sentence_003',
    title: '句子含义：深层含义',
    question: '说说这句话的深层含义。',
    referenceAnswer: '这句话表现人物由逃避到理解的心理变化。',
    studentAnswer: '这句话说明他想明白了。',
    expectedPattern: 'sentence_meaning_v1',
    expectedQuestionType: '句子含义',
    expectedAssessmentMode: 'reasoning_chain',
    expectedMainAbility: '理解',
    expectedRubricKeywords: ['字面含义转换', '情感理解'],
  },
  {
    id: 'metadata_sentence_004',
    title: '句子含义：言外之意',
    question: '请说说文中“窗外的雨终于停了”的言外之意。',
    referenceAnswer: '雨停既指天气变化，也暗示人物内心压抑情绪得到缓解。',
    studentAnswer: '说明雨不下了。',
    expectedPattern: 'sentence_meaning_v1',
    expectedQuestionType: '句子含义',
    expectedAssessmentMode: 'reasoning_chain',
    expectedMainAbility: '理解',
    expectedRubricKeywords: ['字面含义转换', '语境联系'],
  },
  {
    id: 'metadata_sentence_005',
    title: '句子含义：理解画线句',
    question: '结合上下文，理解画线句“那条小路一下子宽了起来”的意思。',
    referenceAnswer: '这句话写出人物心结解开后感到轻松，也表现人与人之间的理解让道路变得开阔。',
    studentAnswer: '小路变宽了。',
    expectedPattern: 'sentence_meaning_v1',
    expectedQuestionType: '句子含义',
    expectedAssessmentMode: 'reasoning_chain',
    expectedMainAbility: '理解',
    expectedRubricKeywords: ['字面含义转换', '语境联系'],
  },
  {
    id: 'metadata_sentence_006',
    title: '句子含义：说说你对某句话的理解',
    question: '结合上下文，说说你对“那条小路一下子宽了起来”这句话的理解。',
    referenceAnswer: '这句话不只是写小路变宽，而是表现人物心结解开后内心变得轻松，也暗示人与人之间的理解让生活变得开阔。',
    studentAnswer: '小路变得更宽了。',
    expectedPattern: 'sentence_meaning_v1',
    expectedQuestionType: '句子含义',
    expectedAssessmentMode: 'reasoning_chain',
    expectedMainAbility: '理解',
    expectedRubricKeywords: ['字面含义转换', '语境联系'],
  },
  {
    id: 'metadata_inference_001',
    title: '推理：心理',
    question: '从父亲反复整理旧书的行为，可以推断出他怎样的心理？',
    referenceAnswer: '可以推断父亲舍不得过去的生活，也珍惜与孩子共同读书的回忆。',
    studentAnswer: '父亲很舍不得旧书。',
    expectedPattern: 'inference_v1',
    expectedQuestionType: '推理',
    expectedAssessmentMode: 'reasoning_chain',
    expectedMainAbility: '推理',
    expectedRubricKeywords: ['文本线索', '推理链'],
  },
  {
    id: 'metadata_inference_002',
    title: '推理：可以看出',
    question: '从这个细节可以看出母亲怎样的心情？',
    referenceAnswer: '可以看出母亲既担心孩子，又为孩子的坚持感到欣慰。',
    studentAnswer: '母亲很担心。',
    expectedPattern: 'inference_v1',
    expectedQuestionType: '推理',
    expectedAssessmentMode: 'reasoning_chain',
    expectedMainAbility: '推理',
    expectedRubricKeywords: ['文本线索', '语境理解'],
  },
  {
    id: 'metadata_inference_003',
    title: '推理：推测原因',
    question: '请推测人物这样做的原因。',
    referenceAnswer: '人物这样做是因为内心仍有牵挂，也希望弥补过去的遗憾。',
    studentAnswer: '因为他还在乎这件事。',
    expectedPattern: 'inference_v1',
    expectedQuestionType: '推理',
    expectedAssessmentMode: 'reasoning_chain',
    expectedMainAbility: '推理',
    expectedRubricKeywords: ['推理链', '结论表达'],
  },
  {
    id: 'metadata_inference_004',
    title: '推理：暗示',
    question: '结尾处老人回头望了一眼，这一细节暗示了什么？',
    referenceAnswer: '暗示老人仍然牵挂村庄和故人，内心有不舍。',
    studentAnswer: '老人不舍得离开。',
    expectedPattern: 'inference_v1',
    expectedQuestionType: '推理',
    expectedAssessmentMode: 'reasoning_chain',
    expectedMainAbility: '推理',
    expectedRubricKeywords: ['文本线索', '推理链'],
  },
  {
    id: 'metadata_inference_005',
    title: '推理：说明了什么',
    question: '小女孩把糖纸小心夹进书里，这一行为说明了什么？',
    referenceAnswer: '说明小女孩珍惜这份善意，也把陌生人的帮助记在心里。',
    studentAnswer: '说明她很喜欢糖纸。',
    expectedPattern: 'inference_v1',
    expectedQuestionType: '推理',
    expectedAssessmentMode: 'reasoning_chain',
    expectedMainAbility: '推理',
    expectedRubricKeywords: ['文本线索', '结论表达'],
  },
  {
    id: 'metadata_character_001',
    title: '人物分析：人物形象',
    question: '请结合文本分析父亲的人物形象。',
    referenceAnswer: '父亲沉默、细心、有责任感，文中多次等待和接送孩子体现了深沉的爱。',
    studentAnswer: '父亲是一个关爱孩子的人。',
    expectedPattern: 'character_analysis_v1',
    expectedQuestionType: '人物形象分析',
    expectedAssessmentMode: 'reasoning_chain',
    expectedMainAbility: '分析',
    expectedRubricKeywords: ['人物特点', '文本依据', '分析说明'],
  },
  {
    id: 'metadata_character_002',
    title: '人物分析：怎样的人',
    question: '父亲是一个怎样的人？',
    referenceAnswer: '父亲是一个沉默、勤劳、关爱孩子的人。',
    studentAnswer: '父亲很好。',
    expectedPattern: 'character_analysis_v1',
    expectedQuestionType: '人物形象分析',
    expectedAssessmentMode: 'reasoning_chain',
    expectedMainAbility: '分析',
    expectedRubricKeywords: ['人物特点', '文本依据'],
  },
  {
    id: 'metadata_character_003',
    title: '人物分析：评价人物',
    question: '结合全文评价父亲。',
    referenceAnswer: '父亲虽然不善表达，却用行动一直关心孩子，是深沉而负责的人。',
    studentAnswer: '父亲很负责。',
    expectedPattern: 'character_analysis_v1',
    expectedQuestionType: '人物形象分析',
    expectedAssessmentMode: 'reasoning_chain',
    expectedMainAbility: '分析',
    expectedRubricKeywords: ['人物特点', '分析说明'],
  },
  {
    id: 'metadata_character_004',
    title: '人物分析：母亲特点',
    question: '文中的母亲有哪些性格特点？请结合内容分析。',
    referenceAnswer: '母亲严厉、细心又充满爱，她用严格要求帮助孩子成长。',
    studentAnswer: '母亲很严厉。',
    expectedPattern: 'character_analysis_v1',
    expectedQuestionType: '人物形象分析',
    expectedAssessmentMode: 'reasoning_chain',
    expectedMainAbility: '分析',
    expectedRubricKeywords: ['人物特点', '文本依据'],
  },
  {
    id: 'metadata_character_005',
    title: '人物分析：塑造人物',
    question: '作者塑造了一个怎样的爷爷形象？',
    referenceAnswer: '爷爷勤劳、朴实、乐于帮助他人，具有乡村长者的温厚品质。',
    studentAnswer: '爷爷很勤劳。',
    expectedPattern: 'character_analysis_v1',
    expectedQuestionType: '人物形象分析',
    expectedAssessmentMode: 'reasoning_chain',
    expectedMainAbility: '分析',
    expectedRubricKeywords: ['人物特点', '分析说明'],
  },
  {
    id: 'metadata_function_001',
    title: '作用分析：物象作用',
    question: '文中多次写“旧自行车”有什么作用？',
    referenceAnswer: '旧自行车贯穿父亲接送孩子的回忆，表现父亲默默的爱。',
    studentAnswer: '旧自行车表现父亲的爱。',
    expectedPattern: 'function_analysis_v1',
    expectedQuestionType: '作用分析',
    expectedAssessmentMode: 'reasoning_chain',
    expectedMainAbility: '分析',
    expectedRubricKeywords: ['分析对象', '作用说明', '主题联系'],
  },
  {
    id: 'metadata_function_002',
    title: '作用分析：段落作用',
    question: '这一段在文中有什么作用？',
    referenceAnswer: '这一段承接前文回忆，引出作者对父爱的理解。',
    studentAnswer: '这一段引出下文。',
    expectedPattern: 'function_analysis_v1',
    expectedQuestionType: '作用分析',
    expectedAssessmentMode: 'reasoning_chain',
    expectedMainAbility: '分析',
    expectedRubricKeywords: ['分析对象', '文本依据', '作用说明'],
  },
  {
    id: 'metadata_function_003',
    title: '作用分析：标题作用',
    question: '文章标题“那盏灯”有何作用？',
    referenceAnswer: '标题点明线索，暗示父亲的牵挂，也寄托作者对父爱的理解。',
    studentAnswer: '标题写了灯。',
    expectedPattern: 'function_analysis_v1',
    expectedQuestionType: '作用分析',
    expectedAssessmentMode: 'reasoning_chain',
    expectedMainAbility: '分析',
    expectedRubricKeywords: ['分析对象', '作用说明'],
  },
  {
    id: 'metadata_function_004',
    title: '作用分析：反复写',
    question: '作者为什么反复写门前那棵树？',
    referenceAnswer: '反复写树既形成文章线索，也见证人物成长和亲情变化。',
    studentAnswer: '因为那棵树很重要。',
    expectedPattern: 'function_analysis_v1',
    expectedQuestionType: '作用分析',
    expectedAssessmentMode: 'reasoning_chain',
    expectedMainAbility: '分析',
    expectedRubricKeywords: ['作用说明', '主题联系'],
  },
  {
    id: 'metadata_function_005',
    title: '作用分析：开头用意',
    question: '文章开头写雨声有什么用意？',
    referenceAnswer: '开头写雨声营造氛围，引出回忆，也烘托人物低落的心情。',
    studentAnswer: '是为了写天气。',
    expectedPattern: 'function_analysis_v1',
    expectedQuestionType: '作用分析',
    expectedAssessmentMode: 'reasoning_chain',
    expectedMainAbility: '分析',
    expectedRubricKeywords: ['分析对象', '主题联系'],
  },
  {
    id: 'metadata_effect_001',
    title: '表达效果：赏析句子',
    question: '请赏析文中画线句子的表达效果。',
    referenceAnswer: '画线句运用细节描写，写出父亲等待时的沉默和执着，表现父亲深沉的爱。',
    studentAnswer: '这句话写得很生动。',
    expectedPattern: 'expression_effect_v1',
    expectedQuestionType: '表达效果',
    expectedAssessmentMode: 'reasoning_chain',
    expectedMainAbility: '分析',
    expectedRubricKeywords: ['表达对象', '表现手法', '效果说明'],
  },
  {
    id: 'metadata_effect_002',
    title: '表达效果：妙处',
    question: '说说这句话好在哪里。',
    referenceAnswer: '这句话通过具体动作描写，生动表现人物内心的不舍。',
    studentAnswer: '好在表现了不舍。',
    expectedPattern: 'expression_effect_v1',
    expectedQuestionType: '表达效果',
    expectedAssessmentMode: 'reasoning_chain',
    expectedMainAbility: '分析',
    expectedRubricKeywords: ['表现手法', '情感主题'],
  },
  {
    id: 'metadata_effect_003',
    title: '表达效果：分析表达效果',
    question: '分析这处细节描写的表达效果。',
    referenceAnswer: '细节描写突出父亲的细心和牵挂，使人物形象更具体。',
    studentAnswer: '表现父亲细心。',
    expectedPattern: 'expression_effect_v1',
    expectedQuestionType: '表达效果',
    expectedAssessmentMode: 'reasoning_chain',
    expectedMainAbility: '分析',
    expectedRubricKeywords: ['表现手法', '效果说明'],
  },
  {
    id: 'metadata_effect_004',
    title: '表达效果：修辞',
    question: '请分析画线句运用比喻修辞的表达效果。',
    referenceAnswer: '比喻把母亲的叮嘱写得具体可感，表现叮嘱给作者带来的温暖和力量。',
    studentAnswer: '用了比喻，很形象。',
    expectedPattern: 'expression_effect_v1',
    expectedQuestionType: '表达效果',
    expectedAssessmentMode: 'reasoning_chain',
    expectedMainAbility: '分析',
    expectedRubricKeywords: ['表现手法', '效果说明'],
  },
  {
    id: 'metadata_effect_005',
    title: '表达效果：用词',
    question: '文中“悄悄地”一词有怎样的表达效果？',
    referenceAnswer: '“悄悄地”写出人物动作轻柔、不愿打扰他人，表现其细心体贴。',
    studentAnswer: '说明动作很轻。',
    expectedPattern: 'expression_effect_v1',
    expectedQuestionType: '表达效果',
    expectedAssessmentMode: 'reasoning_chain',
    expectedMainAbility: '分析',
    expectedRubricKeywords: ['表达对象', '效果说明'],
  },
  {
    id: 'metadata_expression_001',
    title: '表达：仿写',
    question: '请仿写一句话，表达你对亲情的理解。',
    referenceAnswer: '亲情像一盏灯，在我迷路时给我方向。',
    studentAnswer: '亲情像阳光，温暖我的心。',
    expectedPattern: 'expression_task_v1',
    expectedQuestionType: '表达',
    expectedAssessmentMode: 'expression_quality',
    expectedMainAbility: '表达',
    expectedRubricKeywords: ['回应任务', '语言组织'],
  },
  {
    id: 'metadata_expression_002',
    title: '表达：联系生活谈感受',
    question: '联系生活实际，谈谈你读完本文后的感受。',
    referenceAnswer: '读完文章，我想到父母平时默默照顾我，感受到亲情常常藏在日常小事里。',
    studentAnswer: '我想到妈妈每天接我放学，很感动。',
    expectedPattern: 'expression_task_v1',
    expectedQuestionType: '表达',
    expectedAssessmentMode: 'expression_quality',
    expectedMainAbility: '表达',
    expectedRubricKeywords: ['观点明确', '内容支撑'],
  },
  {
    id: 'metadata_expression_003',
    title: '表达：写一段看法',
    question: '请写一段话表达你对文中父亲做法的看法。',
    referenceAnswer: '我认为父亲的做法体现了深沉的爱，他用行动陪伴孩子成长。',
    studentAnswer: '我觉得父亲很爱孩子。',
    expectedPattern: 'expression_task_v1',
    expectedQuestionType: '表达',
    expectedAssessmentMode: 'expression_quality',
    expectedMainAbility: '表达',
    expectedRubricKeywords: ['回应任务', '观点明确'],
  },
  {
    id: 'metadata_expression_004',
    title: '表达：启示',
    question: '这篇文章给了你怎样的启示？请结合自身经历谈一谈。',
    referenceAnswer: '文章启示我们要珍惜亲情，也要学会理解家人沉默背后的关爱。',
    studentAnswer: '我要珍惜家人。',
    expectedPattern: 'expression_task_v1',
    expectedQuestionType: '表达',
    expectedAssessmentMode: 'expression_quality',
    expectedMainAbility: '表达',
    expectedRubricKeywords: ['观点明确', '内容支撑'],
  },
  {
    id: 'metadata_expression_005',
    title: '表达：续写',
    question: '请根据文章结尾续写几句话，表现“我”的心理变化。',
    referenceAnswer: '我望着那盏灯，忽然想起父亲一次次等待的身影，心里涌起歉疚和温暖。',
    studentAnswer: '我很感动，也想感谢父亲。',
    expectedPattern: 'expression_task_v1',
    expectedQuestionType: '表达',
    expectedAssessmentMode: 'expression_quality',
    expectedMainAbility: '表达',
    expectedRubricKeywords: ['回应任务', '语言组织'],
  },
];
