export type QuestionMetadataSample = {
  id: string;
  title: string;
  question: string;
  referenceAnswer: string;
  expectedPattern: string;
  expectedQuestionType: string;
  expectedAssessmentMode: string;
  expectedMainAbility: string;
  expectedRubricKeywords: string[];
};

export const questionMetadataSamples: QuestionMetadataSample[] = [
  {
    id: 'metadata_extraction_001',
    title: '信息提取：找原因',
    question: '根据原文，找出母亲改变主意的两个原因。',
    referenceAnswer: '一是她看见孩子一直坚持练习，二是老师说明孩子确实有进步。',
    expectedPattern: 'information_extraction_v1',
    expectedQuestionType: '信息提取',
    expectedAssessmentMode: 'key_points',
    expectedMainAbility: '信息提取',
    expectedRubricKeywords: ['题干限定', '关键文本', '完整要点'],
  },
  {
    id: 'metadata_extraction_002',
    title: '信息提取：哪几件事',
    question: '文中写了哪几件表现父爱的事？',
    referenceAnswer: '父亲送我上学、在门口等我回家、为我留灯。',
    expectedPattern: 'information_extraction_v1',
    expectedQuestionType: '信息提取',
    expectedAssessmentMode: 'key_points',
    expectedMainAbility: '信息提取',
    expectedRubricKeywords: ['题干限定', '关键文本', '完整要点'],
  },
  {
    id: 'metadata_extraction_003',
    title: '信息提取：找相关句子',
    question: '从文中找出描写父亲等待我的相关句子。',
    referenceAnswer: '父亲仍然习惯站在门口等我。',
    expectedPattern: 'information_extraction_v1',
    expectedQuestionType: '信息提取',
    expectedAssessmentMode: 'key_points',
    expectedMainAbility: '信息提取',
    expectedRubricKeywords: ['题干限定', '关键文本'],
  },
  {
    id: 'metadata_summary_001',
    title: '概括：主要内容',
    question: '请概括文章主要内容。',
    referenceAnswer: '文章回忆父亲送“我”上学和等待“我”回家的经历，表现了父亲深沉而无言的爱。',
    expectedPattern: 'summary_v1',
    expectedQuestionType: '概括',
    expectedAssessmentMode: 'key_points',
    expectedMainAbility: '概括',
    expectedRubricKeywords: ['核心事件', '主题'],
  },
  {
    id: 'metadata_summary_002',
    title: '概括：主要写了什么',
    question: '选文主要写了什么？请简要概括。',
    referenceAnswer: '选文主要写父亲用旧自行车接送孩子，并在孩子长大后仍默默等待的经历。',
    expectedPattern: 'summary_v1',
    expectedQuestionType: '概括',
    expectedAssessmentMode: 'key_points',
    expectedMainAbility: '概括',
    expectedRubricKeywords: ['主要对象', '核心事件'],
  },
  {
    id: 'metadata_summary_003',
    title: '概括：段落大意',
    question: '请概括这一段的段落大意。',
    referenceAnswer: '这一段写作者回家时发现父亲仍在门口等待，从而理解父亲的爱。',
    expectedPattern: 'summary_v1',
    expectedQuestionType: '概括',
    expectedAssessmentMode: 'key_points',
    expectedMainAbility: '概括',
    expectedRubricKeywords: ['核心事件', '表达完整'],
  },
  {
    id: 'metadata_sentence_001',
    title: '句子含义：分析含义',
    question: '请分析“照亮了父亲对我的牵挂”的含义。',
    referenceAnswer: '“照亮”不是指灯光真正照亮，而是指作者通过这盏灯感受到父亲一直以来的关爱和牵挂。',
    expectedPattern: 'sentence_meaning_v1',
    expectedQuestionType: '句子含义',
    expectedAssessmentMode: 'reasoning_chain',
    expectedMainAbility: '理解',
    expectedRubricKeywords: ['字面含义转换', '语境联系', '情感理解'],
  },
  {
    id: 'metadata_sentence_002',
    title: '句子含义：如何理解',
    question: '如何理解文中“他终于放慢了脚步”这句话？',
    referenceAnswer: '这句话写出人物愿意停下来面对问题，表现心理转变。',
    expectedPattern: 'sentence_meaning_v1',
    expectedQuestionType: '句子含义',
    expectedAssessmentMode: 'reasoning_chain',
    expectedMainAbility: '理解',
    expectedRubricKeywords: ['字面含义转换', '语境联系'],
  },
  {
    id: 'metadata_sentence_003',
    title: '句子含义：深层含义',
    question: '说说这句话的深层含义。',
    referenceAnswer: '这句话表现人物由逃避到理解的心理变化。',
    expectedPattern: 'sentence_meaning_v1',
    expectedQuestionType: '句子含义',
    expectedAssessmentMode: 'reasoning_chain',
    expectedMainAbility: '理解',
    expectedRubricKeywords: ['字面含义转换', '情感理解'],
  },
  {
    id: 'metadata_inference_001',
    title: '推理：心理',
    question: '从父亲反复整理旧书的行为，可以推断出他怎样的心理？',
    referenceAnswer: '可以推断父亲舍不得过去的生活，也珍惜与孩子共同读书的回忆。',
    expectedPattern: 'inference_v1',
    expectedQuestionType: '推理',
    expectedAssessmentMode: 'reasoning_chain',
    expectedMainAbility: '推理',
    expectedRubricKeywords: ['文本线索', '推理链'],
  },
  {
    id: 'metadata_inference_002',
    title: '推理：可以看出',
    question: '从这个细节可以看出母亲怎样的心情？',
    referenceAnswer: '可以看出母亲既担心孩子，又为孩子的坚持感到欣慰。',
    expectedPattern: 'inference_v1',
    expectedQuestionType: '推理',
    expectedAssessmentMode: 'reasoning_chain',
    expectedMainAbility: '推理',
    expectedRubricKeywords: ['文本线索', '语境理解'],
  },
  {
    id: 'metadata_inference_003',
    title: '推理：推测原因',
    question: '请推测人物这样做的原因。',
    referenceAnswer: '人物这样做是因为内心仍有牵挂，也希望弥补过去的遗憾。',
    expectedPattern: 'inference_v1',
    expectedQuestionType: '推理',
    expectedAssessmentMode: 'reasoning_chain',
    expectedMainAbility: '推理',
    expectedRubricKeywords: ['推理链', '结论表达'],
  },
  {
    id: 'metadata_character_001',
    title: '人物分析：人物形象',
    question: '请结合文本分析父亲的人物形象。',
    referenceAnswer: '父亲沉默、细心、有责任感，文中多次等待和接送孩子体现了深沉的爱。',
    expectedPattern: 'character_analysis_v1',
    expectedQuestionType: '人物形象分析',
    expectedAssessmentMode: 'reasoning_chain',
    expectedMainAbility: '分析',
    expectedRubricKeywords: ['人物特点', '文本依据', '分析说明'],
  },
  {
    id: 'metadata_character_002',
    title: '人物分析：怎样的人',
    question: '父亲是一个怎样的人？',
    referenceAnswer: '父亲是一个沉默、勤劳、关爱孩子的人。',
    expectedPattern: 'character_analysis_v1',
    expectedQuestionType: '人物形象分析',
    expectedAssessmentMode: 'reasoning_chain',
    expectedMainAbility: '分析',
    expectedRubricKeywords: ['人物特点', '文本依据'],
  },
  {
    id: 'metadata_character_003',
    title: '人物分析：评价人物',
    question: '结合全文评价父亲。',
    referenceAnswer: '父亲虽然不善表达，却用行动一直关心孩子，是深沉而负责的人。',
    expectedPattern: 'character_analysis_v1',
    expectedQuestionType: '人物形象分析',
    expectedAssessmentMode: 'reasoning_chain',
    expectedMainAbility: '分析',
    expectedRubricKeywords: ['人物特点', '分析说明'],
  },
  {
    id: 'metadata_function_001',
    title: '作用分析：物象作用',
    question: '文中多次写“旧自行车”有什么作用？',
    referenceAnswer: '旧自行车贯穿父亲接送孩子的回忆，表现父亲默默的爱。',
    expectedPattern: 'function_analysis_v1',
    expectedQuestionType: '作用分析',
    expectedAssessmentMode: 'reasoning_chain',
    expectedMainAbility: '分析',
    expectedRubricKeywords: ['分析对象', '作用说明', '主题联系'],
  },
  {
    id: 'metadata_function_002',
    title: '作用分析：段落作用',
    question: '这一段在文中有什么作用？',
    referenceAnswer: '这一段承接前文回忆，引出作者对父爱的理解。',
    expectedPattern: 'function_analysis_v1',
    expectedQuestionType: '作用分析',
    expectedAssessmentMode: 'reasoning_chain',
    expectedMainAbility: '分析',
    expectedRubricKeywords: ['分析对象', '文本依据', '作用说明'],
  },
  {
    id: 'metadata_effect_001',
    title: '表达效果：赏析句子',
    question: '请赏析文中画线句子的表达效果。',
    referenceAnswer: '画线句运用细节描写，写出父亲等待时的沉默和执着，表现父亲深沉的爱。',
    expectedPattern: 'expression_effect_v1',
    expectedQuestionType: '表达效果',
    expectedAssessmentMode: 'reasoning_chain',
    expectedMainAbility: '分析',
    expectedRubricKeywords: ['表达对象', '表现手法', '效果说明'],
  },
  {
    id: 'metadata_effect_002',
    title: '表达效果：妙处',
    question: '说说这句话好在哪里。',
    referenceAnswer: '这句话通过具体动作描写，生动表现人物内心的不舍。',
    expectedPattern: 'expression_effect_v1',
    expectedQuestionType: '表达效果',
    expectedAssessmentMode: 'reasoning_chain',
    expectedMainAbility: '分析',
    expectedRubricKeywords: ['表现手法', '情感主题'],
  },
  {
    id: 'metadata_effect_003',
    title: '表达效果：分析表达效果',
    question: '分析这处细节描写的表达效果。',
    referenceAnswer: '细节描写突出父亲的细心和牵挂，使人物形象更具体。',
    expectedPattern: 'expression_effect_v1',
    expectedQuestionType: '表达效果',
    expectedAssessmentMode: 'reasoning_chain',
    expectedMainAbility: '分析',
    expectedRubricKeywords: ['表现手法', '效果说明'],
  },
  {
    id: 'metadata_expression_001',
    title: '表达：仿写',
    question: '请仿写一句话，表达你对亲情的理解。',
    referenceAnswer: '亲情像一盏灯，在我迷路时给我方向。',
    expectedPattern: 'expression_task_v1',
    expectedQuestionType: '表达',
    expectedAssessmentMode: 'expression_quality',
    expectedMainAbility: '表达',
    expectedRubricKeywords: ['回应任务', '语言组织'],
  },
  {
    id: 'metadata_expression_002',
    title: '表达：联系生活谈感受',
    question: '联系生活实际，谈谈你读完本文后的感受。',
    referenceAnswer: '读完文章，我想到父母平时默默照顾我，感受到亲情常常藏在日常小事里。',
    expectedPattern: 'expression_task_v1',
    expectedQuestionType: '表达',
    expectedAssessmentMode: 'expression_quality',
    expectedMainAbility: '表达',
    expectedRubricKeywords: ['观点明确', '内容支撑'],
  },
  {
    id: 'metadata_expression_003',
    title: '表达：写一段看法',
    question: '请写一段话表达你对文中父亲做法的看法。',
    referenceAnswer: '我认为父亲的做法体现了深沉的爱，他用行动陪伴孩子成长。',
    expectedPattern: 'expression_task_v1',
    expectedQuestionType: '表达',
    expectedAssessmentMode: 'expression_quality',
    expectedMainAbility: '表达',
    expectedRubricKeywords: ['回应任务', '观点明确'],
  },
];
