import { runRealAIDiagnosisLoop } from '../agents/realAIDiagnosisAgent.ts';
import { generateTrainingPlan } from '../agents/trainingPlanAgent.ts';
import { isAbilityEvidence, normalizeAbilityEvidence } from '../schemas/abilityEvidence.schema.ts';
import { isStudentAbilityProfile } from '../schemas/studentAbilityProfile.schema.ts';
import { isTrainingPlan } from '../schemas/trainingPlan.schema.ts';
import type { DiagnosisResult } from '../schemas/diagnosis.schema.ts';

const previousEvidence = [
  normalizeAbilityEvidence({
    id: 'phase42-previous-expression-001',
    studentId: 'demo-student',
    ability: '表达',
    evidenceType: 'weakness',
    source: 'diagnosis',
    observation: '学生能表达观点，但缺少文本依据和说明。',
    rootCause: '观点、依据、说明的表达结构不稳定。',
    confidence: 0.66,
    createdAt: '2026-07-09T09:00:00.000Z',
    taskId: 'phase42-previous-task-001',
    diagnosisId: 'phase42-previous-diagnosis-001',
  }),
  normalizeAbilityEvidence({
    id: 'phase42-previous-summary-001',
    studentId: 'demo-student',
    ability: '概括',
    evidenceType: 'positive',
    source: 'diagnosis',
    observation: '学生能概括核心事件和主要情感。',
    confidence: 0.79,
    createdAt: '2026-07-09T09:05:00.000Z',
    taskId: 'phase42-previous-task-002',
    diagnosisId: 'phase42-previous-diagnosis-002',
  }),
];

const sampleInput = {
  studentId: 'demo-student',
  previousEvidence,
  taskId: 'phase42-real-ai-task-001',
  diagnosisId: 'phase42-real-ai-diagnosis-001',
  createdAt: '2026-07-09T10:00:00.000Z',
  question: '结合上下文，说说你对“那盏灯不仅照亮了回家的路，也照亮了父亲对我的牵挂”这句话的理解。',
  referenceAnswer: '这句话中“照亮”不只是指灯光照亮道路，更指作者通过那盏灯感受到父亲长期默默的关爱和牵挂，表达了作者对父爱的理解与感动。',
  studentAnswer: '这句话表现了父亲很爱我，我很感动。',
};

async function runRealAIDiagnosisDebug(): Promise<void> {
  const result = await runRealAIDiagnosisLoop(sampleInput);
  const failures: string[] = [];

  validateDiagnosisResult(result.diagnosisResult, failures);
  validateEvidenceAndProfile(result, failures);
  printReport(result, failures);

  if (failures.length > 0) {
    throw new Error('Real AI Diagnosis debug check failed.');
  }
}

function validateDiagnosisResult(diagnosisResult: DiagnosisResult, failures: string[]): void {
  if (!diagnosisResult.mainAbility) failures.push('Diagnosis Result missing mainAbility.');
  if (!diagnosisResult.rootCause) failures.push('Diagnosis Result missing rootCause.');
  if (!Array.isArray(diagnosisResult.abilityEvidence) || diagnosisResult.abilityEvidence.length === 0) {
    failures.push('Diagnosis Result missing abilityEvidence.');
  }
  if (!diagnosisResult.diagnosisSummary) failures.push('Diagnosis Result missing diagnosisSummary.');
  if (!diagnosisResult.nextTraining) failures.push('Diagnosis Result missing nextTraining.');
  if (
    typeof diagnosisResult.confidence !== 'number' ||
    Number.isNaN(diagnosisResult.confidence) ||
    diagnosisResult.confidence < 0 ||
    diagnosisResult.confidence > 1
  ) {
    failures.push('Diagnosis Result confidence must be a number between 0 and 1.');
  }
}

function validateEvidenceAndProfile(
  result: Awaited<ReturnType<typeof runRealAIDiagnosisLoop>>,
  failures: string[],
): void {
  if (!result.prompt.includes('Real AI Diagnosis Agent')) {
    failures.push('Prompt should be generated by Real AI Diagnosis Prompt Builder.');
  }

  if (!isAbilityEvidence(result.abilityEvidence)) {
    failures.push('Ability Evidence should match AbilityEvidence schema.');
  }

  if (result.abilityEvidence.id !== result.newAbilityEvidence.id) {
    failures.push('abilityEvidence should remain a compatibility alias of newAbilityEvidence.');
  }

  if (result.abilityEvidence.source !== 'diagnosis') {
    failures.push('Ability Evidence source should be diagnosis.');
  }

  if (result.updatedEvidence.length !== previousEvidence.length + 1) {
    failures.push('updatedEvidence should equal previousEvidence plus newAbilityEvidence.');
  }

  if (!result.updatedEvidence.some((item) => item.id === result.newAbilityEvidence.id)) {
    failures.push('updatedEvidence should include newAbilityEvidence.');
  }

  if (result.evidenceSummary.length === 0) {
    failures.push('evidenceSummary should be generated from updatedEvidence.');
  }

  if (result.topWeakness.length === 0) {
    failures.push('topWeakness should be generated from updatedEvidence.');
  }

  const trainingPlan = generateTrainingPlan({
    studentId: sampleInput.studentId,
    weaknessRanking: result.topWeakness,
    evidenceSummary: result.evidenceSummary,
    generatedAt: sampleInput.createdAt,
  });

  if (!isTrainingPlan(trainingPlan)) {
    failures.push('Training Plan should be generatable from Phase 4.2 evidenceSummary and topWeakness.');
  }

  if (!isStudentAbilityProfile(result.studentAbilityProfile)) {
    failures.push('Student Ability Profile should match schema.');
  }

  if (result.studentAbilityProfile.evidence_links.length === 0) {
    failures.push('Student Ability Profile should include evidence_links.');
  }
}

function printReport(
  result: Awaited<ReturnType<typeof runRealAIDiagnosisLoop>>,
  failures: string[],
): void {
  console.log('\nReal AI Diagnosis Debug Report');
  console.log('==============================');
  console.log(`usedLiveAI: ${result.usedLiveAI}`);
  console.log(`promptLength: ${result.prompt.length}`);
  console.log(`questionType: ${result.questionMetadata?.questionType || 'unknown'}`);
  console.log(`mainAbility: ${result.diagnosisResult.mainAbility}`);
  console.log(`answerStatus: ${result.diagnosisResult.answerStatus || 'unknown'}`);
  console.log(`rootCause: ${result.diagnosisResult.rootCause}`);
  console.log(`confidence: ${formatPercent(result.diagnosisResult.confidence)}`);

  console.log('\nRuntime Evidence Flow');
  console.log('---------------------');
  console.log(`previousEvidence: ${previousEvidence.length}`);
  console.log(`newAbilityEvidence: ${result.newAbilityEvidence.id}`);
  console.log(`updatedEvidence: ${result.updatedEvidence.length}`);

  console.log('\nNew Ability Evidence');
  console.log('--------------------');
  console.log(`id: ${result.newAbilityEvidence.id}`);
  console.log(`ability: ${result.newAbilityEvidence.ability}`);
  console.log(`evidenceType: ${result.newAbilityEvidence.evidenceType}`);
  console.log(`source: ${result.newAbilityEvidence.source}`);
  console.log(`observation: ${result.newAbilityEvidence.observation}`);

  console.log('\nEvidence Summary');
  console.log('----------------');
  for (const summary of result.evidenceSummary) {
    console.log(`${summary.ability}: weakness ${summary.weaknessCount}, positive ${summary.positiveCount}, growth ${summary.growthCount}, insufficient ${summary.insufficientCount}`);
  }

  console.log('\nTop Weakness');
  console.log('------------');
  for (let index = 0; index < result.topWeakness.length; index += 1) {
    const item = result.topWeakness[index];
    console.log(`${index + 1}. ${item.ability} | weakness ${item.weaknessCount} | confidence ${formatPercent(item.averageConfidence)}`);
  }

  const trainingPlan = generateTrainingPlan({
    studentId: sampleInput.studentId,
    weaknessRanking: result.topWeakness,
    evidenceSummary: result.evidenceSummary,
    generatedAt: sampleInput.createdAt,
  });

  console.log('\nDownstream Handoff');
  console.log('------------------');
  console.log(`trainingPlanReady: ${isTrainingPlan(trainingPlan)}`);
  console.log(`primaryTargetAbility: ${trainingPlan.primary_target_ability}`);

  console.log('\nStudent Ability Profile');
  console.log('-----------------------');
  console.log(`primary weakness: ${result.studentAbilityProfile.current_weakness.primary}`);
  console.log(`next step: ${result.studentAbilityProfile.next_step_recommendation}`);

  console.log('\nStable JSON Output');
  console.log('------------------');
  console.log(JSON.stringify({
    diagnosisResult: result.diagnosisResult,
    newAbilityEvidence: result.newAbilityEvidence,
    updatedEvidence: result.updatedEvidence,
    evidenceSummary: result.evidenceSummary,
    topWeakness: result.topWeakness,
    studentAbilityProfile: result.studentAbilityProfile,
    usedLiveAI: result.usedLiveAI,
  }, null, 2));

  console.log('\nAcceptance');
  console.log('----------');
  if (failures.length === 0) {
    console.log('[PASS] Real AI Diagnosis runtime handoff loop is structurally ready.');
  } else {
    console.log('[FAIL] Real AI Diagnosis runtime handoff loop did not meet structural acceptance.');
    for (const failure of failures) {
      console.log(`- ${failure}`);
    }
  }
}

function formatPercent(value: number): string {
  return `${Math.round(value * 100)}%`;
}

runRealAIDiagnosisDebug().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
});
