import { useState } from 'react';
import { AlertTriangle, ArrowLeft, CheckCircle2, FlaskConical, LoaderCircle } from 'lucide-react';
import { Link } from 'react-router-dom';
import { runProductRuntimeReliabilityWPR1BrowserAcceptance } from '../api/productRuntimeReliabilityWPR1BrowserAcceptance.ts';

export default function ProductRuntimeReliabilityWPR1Acceptance() {
  const [report, setReport] = useState(null); const [running, setRunning] = useState(false); const [error, setError] = useState('');
  async function runMatrix() { if (running) return; setRunning(true); setError(''); try { setReport(await runProductRuntimeReliabilityWPR1BrowserAcceptance()); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } finally { setRunning(false); } }
  const completed = report && report.passed === report.total;
  return <div className="min-h-screen bg-[#f7f9fc] text-slate-950" data-testid="product-runtime-wp-r1-acceptance">
    <header className="border-b border-slate-200 bg-white"><div className="mx-auto flex min-h-16 max-w-[1100px] items-center gap-4 px-5 md:px-8"><Link to="/internal/acceptance" aria-label="返回验收入口" className="flex h-10 w-10 items-center justify-center rounded-md border border-slate-200"><ArrowLeft size={18}/></Link><div><h1 className="text-lg font-semibold">运行可靠性 WP-R1</h1><p className="text-sm text-slate-500">R1-B01—R1-B14 · Launcher 与 Health 只读验收</p></div></div></header>
    <main className="mx-auto max-w-[1100px] px-5 py-8 md:px-8"><section className="rounded-lg border border-slate-200 bg-white p-6"><div className="flex flex-wrap justify-between gap-5"><div><h2 className="text-xl font-semibold">Runtime Health 浏览器矩阵</h2><p className="mt-2 text-sm text-slate-600">只执行 GET，不启动或停止服务，不写正式资源、学习事实或 Trial。</p></div><button type="button" onClick={runMatrix} disabled={running} data-testid="run-product-runtime-wp-r1-browser-matrix" className="flex min-h-11 min-w-[220px] items-center justify-center gap-2 rounded-md bg-emerald-600 px-5 text-sm font-medium text-white disabled:opacity-60">{running ? <><LoaderCircle className="animate-spin" size={17}/>检查中…</> : <><FlaskConical size={17}/>执行 R1-B01—R1-B14</>}</button></div>{error ? <div role="alert" className="mt-5 rounded-md bg-red-50 p-4 text-red-700">{error}</div> : null}{report ? <div data-testid="product-runtime-wp-r1-summary" className={`mt-5 flex items-center gap-3 rounded-md p-4 ${completed ? 'bg-emerald-50 text-emerald-800' : 'bg-red-50 text-red-800'}`}>{completed ? <CheckCircle2 size={22}/> : <AlertTriangle size={22}/>}<div><p className="font-semibold">{report.passed}/{report.total} {completed ? '全部通过' : '存在未通过项'}</p><p className="text-xs">Overall：{report.overallStatus} · Revision：{report.formalResourceRevision}</p></div></div> : null}</section>
      <section className="mt-6">{!report ? <p className="rounded-md border border-slate-200 bg-white p-5 text-sm text-slate-600">尚未执行矩阵。</p> : <div className="divide-y divide-slate-200 overflow-hidden rounded-lg border border-slate-200 bg-white">{report.checks.map((item) => <article key={item.id} data-check-id={item.id} className="grid gap-3 p-5 md:grid-cols-[88px_210px_1fr_64px]"><code className="text-sm font-semibold text-slate-500">{item.id}</code><h3 className="text-sm font-semibold">{item.title}</h3><p className="text-sm text-slate-600">{item.evidence}</p><span className={`text-xs font-semibold ${item.passed ? 'text-emerald-700' : 'text-red-700'}`}>{item.passed ? 'PASS' : 'FAIL'}</span></article>)}</div>}</section>
    </main>
  </div>;
}
